### PR TITLE
Remove redundant get when accessing element in unique_ptr array

### PR DESCRIPTION
**Pull request by alexandear**
I'm a member of the [Pinguem.ru](https://pinguem.ru) competition on finding errors in open source projects. Issue was found with [PVS-Studio](https://www.viva64.com/en/pvs-studio/):
* V527 It is odd that the '\0' value is assigned to 'char' type pointer. Probably meant: *buff.get()[filesize] = '\0'. tgitpath.cpp 770

### CODE REVIEW

**Comment by csware** [comment]
Thanks for this PR, actually the code is correct and is that way becasue older versions of VS did not handle the array syntax directly.

**Comment by alexandear** [comment]
@csware added signed-off

**Comment by csware** [comment]
Merged with commit fb7cc4ff18fcfea67c200b01f0bda9e7866ab5e5.

**Comment by csware** [comment]
Thank you.

**Pull request closed without merging**
