### PR TITLE
[Issue #3738] Added force flag on LFSLocks Dialog

### PR DESCRIPTION
**Pull request by lpestl**
A **detailed description** of the [issue#3738](https://gitlab.com/tortoisegit/tortoisegit/-/issues/3738) that can be solved by this PR (as one of the options) can be read here:
https://gitlab.com/tortoisegit/tortoisegit/-/issues/3738

Visually, it looks like this:

### CODE REVIEW

**Comment by lpestl** [comment]
@csware , I am discouraged. Can't figure out why AppVeyor build failed...

**Comment by csware** [comment]
The translation file is not up2date. You need to execute the "TortoisePot" target to update `Tortoise.pot`.

**Comment by csware** [comment]
The translation file is not up2date. You need to execute the "TortoisePot" target to update `Tortoise.pot`.

**Comment by lpestl** [comment]
Rebased onto last commit of the master

**Comment by lpestl** [comment]
> The translation file is not up2date. You need to execute the "TortoisePot" target to update Tortoise.pot.
Thank you! It worked

**Comment by csware** [comment]
Looks good to me, thy did you need to change the size of the dialog?

**Comment by lpestl** [comment]
> Looks good to me, why did you need to change the size of the dialog?

I don't know how the word "force" is spelled in different languages. Perhaps in some of the languages it will turn out to be a long word. And so that the text did not overlap with the "unlock" button or the inscription "select / deselect all", I had to slightly increase the width of the window.

**Comment by lpestl** [comment]
When I pondered your question, I realized that I (1) hadn't increased the window width enough. The width needs to be increased by a few tens of pixels. (2) I forgot to set the minimum width to a new value (by the way, I don't know where to do this).
Let me explain why you need to increase the width of the dialog a little more:
Now the inscription "Select / Deselect all" in Catalan is written as "Selecciona/Desselecciona tots". And already it does not fit inside the area that is set for the control (by the way, I did not change this width). And the inscription "Force" for example in Russian is written as "Принудительно", which even with my increased size does not fit into the control area. Something like this looks like:
image

@csware Do I need to fix this? Or is it better not to touch? I'm afraid to break something...

**Comment by csware** [comment]
I'll take care.

**Pull request merged**
