### PR TITLE
GitAdminDir cleanup

### PR DESCRIPTION
**Pull request by csware**
Do we need a GitdminDir object (as TSVN has, for the ASP.NET hack) or can we use static methods?

I think we can use static methods, do I overlook something?

### CODE REVIEW

**Comment by ch3cooli** [comment]
Where and what is the ASP.NET hack?

**Comment by csware** [comment]
https://svn.apache.org/repos/asf/subversion/trunk/notes/asp-dot-net-hack.txt
And we don't need to initialize any apr pools or something.

**Comment by ch3cooli** [comment]
I think we do not need GitAdminDir object, as it has no member variable.
Static methods are enough.

**Comment by csware** [comment]
@ch3cooli Thanks for the feedback!
Merged.

**Pull request closed without merging**
