### PR TITLE
Dev gordon update issue 44

### PR DESCRIPTION
**Pull request by flemingg**
Fixed issue #44.
Addressed comments regarding const modifier.
Addressed comments regarding informing user that not all sandbox paths are being show.
Added function for handling parameterized resource table strings to support previous request.

### CODE REVIEW

**Comment by YueLinHo** [comment]
???

**Comment by flemingg** [comment]
Sorry accidental pull request to wrong repo from fork repo.

**Comment by YueLinHo** [comment]
How these happen? I just want to know.

**Comment by flemingg** [comment]
I am working off a repo that was forked previously before my fork.  When a pull request is created the default base fork is the original top level fork.  We have to explicitly change it to ours (sometimes we forget).

**Comment by YueLinHo** [comment]
Thanks for reply.

BTW, your PR is pretty long, is that normal?

**Comment by ch3cooli** [comment]
Could you fork your repo from `PTC-ALM/TortoiseSI` to prevent from opening pull request to the wrong repo in the future?

**Comment by ch3cooli** [comment]
@flemingg Could you fork your repo from PTC-ALM/TortoiseSI to prevent from opening pull request to the wrong repo in the future?

**Pull request closed without merging**
