### PR TITLE
Allow to compare files with deleted files in CommitDlg

### PR DESCRIPTION
**Pull request by csware**
For this select two files and then select "Compare two files". For deleted files the HEAD version is used for comparison. - This is especially helpful for renames.

As requested in https://code.google.com/p/tortoisegit/issues/detail?id=1440#c14

### CODE REVIEW

**Comment by csware** [comment]
Is this misleading?

**Comment by YueLinHo** [comment]
misleading? which part? (I am reading the issue 1440.)

**Comment by csware** [comment]
@YueLinHo When selecting a deleted file for comparison it doesn't use an empty file but the HEAD version.

**Comment by YueLinHo** [comment]
For me, no misleading. Actually, intuitive.

**Comment by YueLinHo** [comment]
@csware 
I can NOT build the source code for now, and I don't familar with this part of code.
I have a question. Does it also work in Log dialog? or only for Commit dialog?

**Comment by csware** [comment]
No support for LogDialog.

This also doesn't work for delete-modify conflicts where the file is deleted in the first parent (locally)

**Comment by YueLinHo** [comment]
I will test it tomorrow. You can merge it anyway, or wait for my testing. :-)

**Comment by csware** [comment]
Merged.

**Comment by YueLinHo** [comment]
Tested. ([ref](https://github.com/YueLinHo/TortoiseGit/commit/4b8c4ad64eb0f3d0ddb1e166b1b317da0c0ac640))
(Then, see the merge.) :)

**Pull request closed without merging**
