### PR TITLE
Do not automatically remove files from repository on commit

### PR DESCRIPTION
**Pull request by csware**
https://code.google.com/p/tortoisegit/issues/detail?id=836

 * [x] Introduce MISSING status
 * [x] Do not autoselect missing files
 * [x] Make setting for above configurable

### CODE REVIEW

**Comment by ch3cooli** [comment]
MISSING status means the user directly deletez the file, without calling `git rm`?

**Comment by csware** [comment]
Exactly. This status will be ORed to the DELETED status, so that we do not need to change all DELETE checks.

**Comment by csware** [comment]
Merged.

**Comment by SpoonMan999** [comment]
Is this the same behavior as TortoiseSVN?
I think that if there are one or more files in a commit flagged as "missing" the commit should be blocked (commit button grayed out, or something like that) until the user explicitly disambiguates whether a file should be really deleted from the repository or restored on the local filesystem.

**Pull request closed without merging**
