### PR TITLE
Additional Overlay Icons

### PR DESCRIPTION
**Pull request by mganss**
I have added four more overlay icon sets. They are based on icon sets by [Axialis Software](http://www.axialis.com) who have kindly given permission for them to be used in TortoiseGit.

### CODE REVIEW

**Comment by csware** [comment]
I didn't had the change for looking at the icons, but can you please squash the commits and add a "Signed-Off-by" line and at best a small reference regarding the permission.

**Comment by ch3cooli** [comment]
Looks cool!
BTW, do we need 256x256 size icons (only found in Flat and Illustration icon set)?

**Comment by mganss** [comment]
256x256 icons are used in the "Extra large icons" view in Windows Explorer. The "Professional" object pack and the "Ribbon & Toolbar" icon set do not have the 256x256 size. Other icon sets in TortoiseGit also have 256x256 icons, e.g. XPStyle. Note that the 256x256 icon is compressed, it adds only ~4KB to the total ~20KB of a single ico.

Google Drive and Microsoft OneDrive both have these sizes: 16x16, 32x32, 48x48, 256x256, only 32-bit, no 8-bit.

**Comment by csware** [comment]
So, can/are you going to provide 256x256 icons?

Regarding the permission: Did you ask by mail? Can you please include the message-id of the answer in the commit msg?

**Comment by mganss** [comment]
I've added 256x256 icons for Professional, but these are upscaled from 192x192 (highest resolution the image object pack provides). The Toolbar & Ribbon set has 48x48 max. I'll ask Axialis if they can provide a higher resolution.

Re permission: Yes, mail. I've added the Message-ID.

**Comment by csware** [comment]
Any news on this?

**Comment by mganss** [comment]
No, I haven't heard back from them yet. Will follow up now.

**Comment by csware** [comment]
TortoiseGit 1.8.16 is on it's way. So, any news?

**Comment by mganss** [comment]
No feedback yet :disappointed: 

Since the 256x256 icons are only missing for the "Toolbar & Ribbon" set, I suggest you include the current icons and I'll add the 256x256 later.

**Comment by csware** [comment]
Merged. Thanks!

**Comment by csware** [comment]
@mganss Can you forward the mail to me? Is there are concrete license for the icons mentioned? Is the TortiseSVN project also allowed to use the icons?

**Comment by mganss** [comment]
Sure. What's the mail address? Mine is public on the GitHub profile page.

I've only explicitly asked for permission to include the icons in TortoiseGit, but the permission given doesn't preclude use in other Tortoise* projects AFAICT. If it is deemed necessary to get explicit permission for TortoiseSVN as well, I can ask Axialis, though I wouldn't expect a fast response :snail: 

There are no "standard" license terms. There are, however, two distinct "regular" license terms: One for the [stock icons](http://www.axialis.com/stock-icons/license.html) (which the Flat and Ribbon icons are based on) and one for the [image object packs](http://www.axialis.com/objects/agreement_toolbar_objects.html) (which the Professional and Illustration icons are based on). Both are geared toward use in closed source commercial applications, which is why I have obtained permission specifically for TortoiseGit.

**Comment by csware** [comment]
Permission for all Tortoise* clients would be perfect. sven@tortoisegit.org

**Pull request closed without merging**
