### PR TITLE
Fixed issue #2437: Add a "Now" button to 'Commit' - 'Set author date' side

### PR DESCRIPTION
**Pull request by yfdyh000**
https://code.google.com/p/tortoisegit/issues/detail?id=2437

It still have a troublesome problem, the width of the button will automatically adapts to the width of English text instead of the translation text. and the `AdjustControlSize` seems inability to deal the width of button.

### CODE REVIEW

**Comment by ch3cooli** [comment]
Your approach is to add a Now button.
However, there may be little time difference (a few seconds) between clicking Now button and OK button. author time + X = commit time

Pull request #161 always makes author time = commit time = now

**Comment by yfdyh000** [comment]
I was expected a button to bring greater flexibility (quickly adjust the approximate time based the current time), and a small loss of accuracy.
But indeed, a checkbox probably is a better solution, I forgot about it.

**Comment by csware** [comment]
@yfdyh000 Please use a real name as author name and signed-off-by-line

**Comment by yfdyh000** [comment]
@csware It is a necessary condition for this project? I really want to use a pseudonym on web, even to give up some rights...

**Comment by csware** [comment]
@yfdyh000 Yeah, that's a good reason indeed. We need to discuss that.

**Comment by YueLinHo** [comment]
@yfdyh000 
In my opinion, pseudonym can be used for contribution.

In my case, I don't only want to contribute, but also make friends with hackers.
So, I show @csware my real name, my real picture, where I come from, what I did, how old I am, what kind of cell phone I used, ..., (wow~ really lots things. :p )
Oh~ These also are not the necessary condition to make friends. :)
(@lznuaa sorry, I don't show you myself.)
So, you know, it is just my case.

Contribution is good, but let reviewers knows who you are is better.
Reviewer needs more time to review the code from someone he does not know.
So, I will suggest you mail something to @csware with a real name.
I think you can continue to contribute with pseudonym.

**Comment by YueLinHo** [comment]
Recommend a nice [book](http://en.wikipedia.org/wiki/The_Hacker_Ethic_and_the_Spirit_of_the_Information_Age)
([Chinese](http://www.books.com.tw/products/0010185886))

**Pull request closed without merging**
