### PR TITLE
Not all remotes showing in Push dialog

### PR DESCRIPTION
**Pull request by duncansmart**
I have a project with more than 25 remotes, so I wasn't finding the remote in the Remote drop down in the Push dialog.

### CODE REVIEW

**Comment by csware** [comment]
@duncansmart It's possible to force push to the same branch for updating a pull request.

**Comment by csware** [comment]
Thanks!
Are other dialogs affected as well?

**Comment by csware** [comment]
Could you please add a Signed-Off-By line? (see https://github.com/TortoiseGit/TortoiseGit/blob/master/doc/HowToContribute.txt)

**Comment by duncansmart** [comment]
OK added the "signed off by"

**Comment by ch3cooli** [comment]
Same problem for pull/fetch dialog.

**Comment by csware** [comment]
@duncansmart Are you updating this PR for also fixing SyncDlg and Pull/Fetch Dlg?

**Comment by duncansmart** [comment]
I will have a go ;-)

**Comment by csware** [comment]
Thanks for the PR, merged!

**Pull request closed without merging**
