### PR TITLE
Extend GitWCRev to return the number of commits.

### PR DESCRIPTION
**Pull request by stefankueng**
This is a number that's guaranteed to only increase and can be used as part of a version number. Similar to the last-commit-revision in Subversion
* add replacement chars $WCLOGCOUNT$, $WCLOGCOUNT&$, $WCLOGCOUNT+$ and $WCLOGCOUNT-$
* add COM property CommitCount
* document the changes

Signed-off-by: Stefan Küng <stefankueng@gmail.com>

### CODE REVIEW

**Comment by csware** [comment]
Actually the commit count is not unique and might cause issues when relied upon. In TGit we already have a commit count (branch rev number) which is based on the first parent only (cf. https://gitlab.com/tortoisegit/tortoisegit/issues/1772 and https://gitlab.com/tortoisegit/tortoisegit/merge_requests/1).

I think we should rewrite this to correspondent to that number.

**Comment by stefankueng** [comment]
Sure the commit count is not unique. But that's not necessary for use as part of a version number. The only requirement of such a number as required in gitwcrev is that the number increases.
Also I'm new to Git, so I don't quite understand the problem you refer to.

**Comment by csware** [comment]
This number is highly dependant on the current branch - if you switch between feature branches this number actually *can* decrease.

**Comment by stefankueng** [comment]
Yes, if you switch between branches then the number can decrease. But never on the same branch.
And that's what's required for a 'patch' release number.
That's also similar to the last-committed revision in Subversion: getting that revision on a release tag will have a lower number than the trunk.

**Comment by csware** [comment]
> That's also similar to the last-committed revision in Subversion

Good point! We should just mention that in the docs...

**Comment by csware** [comment]
When I use this (e.g., insert the following text into Test.tmpl) I get a heap corruption.

```
char *RevisionCount               = "$WCLOGCOUNT$";
char *RevisionCount16             = "$WCLOGCOUNT&0xFF$";
char *RevisionCountp100           = "$WCLOGCOUNT+100$";
char *RevisionCountm100           = "$WCLOGCOUNT-100$";
```

Also `$WCLOGCOUNT$` is not expanded.

**Comment by stefankueng** [comment]
The heap corruption has nothing to do with this change: it happens simply because you extended the test file with more replacement tokens than the 4kb buffer margin can handle.
I've increased the buffer and fixed the other things you mentioned.

**Comment by csware** [comment]
The heap corruption has its origin in the fact that lots of `* sizeof(wchar_t)`were missing.

**Pull request merged**
