### PR TITLE
Add full support for Git for Windows 2.x

### PR DESCRIPTION
**Pull request by csware**

### CODE REVIEW

**Comment by ch3cooli** [comment]
`ProjectProperties.cpp` did not change the path to system config

**Comment by csware** [comment]
ProjectProperties and SettingGitCredential.cpp updated. Thanks @ch3cooli for pointing this out.

**Comment by csware** [comment]
Ok to merge and create a preview release?

**Comment by csware** [comment]
@ch3cooli Thanks for all the comments!

**Pull request merged**
