### PR TITLE
Fix for Issue #2781

### PR DESCRIPTION
**Pull request by AJH16**
SVNRebaseCommand should not stop execution when closeonend is set for closing with no errors.

https://tortoisegit.org/issue/2781

### CODE REVIEW

**Comment by csware** [comment]
Please add a Signed-off-by line and adjust the commit message (Do not show "everything is up to date" when autoclose is requested

Fixes issue #2781.")

**Comment by AJH16** [comment]
Ok, took a bit to figure out how to deal with changing the commit, but I think it should be good now.  Let me know if it needs anything else.

**Comment by csware** [comment]
Have you tested this? A few lines above progress.m_AutoClose is set to AUTOCLOSE_IF_NO_ERRORS.

**Comment by AJH16** [comment]
I did not test the negative case, only the positive. It came up today as I was converting an update script from svn to git svn and it started hanging since it was not properly preventing the dialog from displaying.
I did notice that other set but wasn't sure of the purpose since I couldn't find any documentation on the svnrebase command.  It is possible that set may be in error as well, but it is certainly an error that a success status dialog appears when the command line is asking for silent close on no errors.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by YueLinHo** [comment]
I'd like to use this for commit message
```
Fixed issue #2781: SVNRebase Command does not respect closeonend

Do not show "everything is up to date" when autoclose is requested.
```
(of cause plus the signed-off-by)

And add an entry to `src\Changelog.txt` under `== Bug Fixes ==`, suppose it is
```
 * Fixed issue #2781: SVNRebase Command does not respect closeonend
```

**Comment by YueLinHo** [comment]
Note the code above the changes of this PR, say line 102:
```
 	progress.m_AutoClose = AUTOCLOSE_IF_NO_ERRORS;
```

**Comment by YueLinHo** [comment]
Note the code above the changes of this PR, say line 102:
```
 	progress.m_AutoClose = AUTOCLOSE_IF_NO_ERRORS;
```
Suppose this line need to be deleted.

**Comment by YueLinHo** [comment]
Note the code above the changes of this PR, say line 102:
```
 	progress.m_AutoClose = AUTOCLOSE_IF_NO_ERRORS;
```
I think the `progress.m_AutoClose` value need to be backup before this line and restore it after `DoModal()`.

**Comment by YueLinHo** [comment]
@csware If we are good for this change, which don't show that "everything is up to date" message box, I'd like also to have the next change which don't show "**Fast Forward**" message box.

@AJH16 another comment for you: using `L""` for `_T("")`.

**Comment by AJH16** [comment]
Ok, so I take it you guys prefer a "fix anything you see" vs "highly direct to whatever the issue is" approach to fixes then?  Wasn't sure how you liked the granularity for outside contributions.The _T was another thing that I just left alone, though thanks for pointing it out as I haven't used C++ seriously since the mid 2000s, and then in an academic context, so I wasn't even familiar with the meaning of L"" or _T"".

**Comment by csware** [comment]
I haven't said anything about L"" or _T"". as this is clearly a side issue, which can be addressed by us. So, no need to care for you.

So, I'd recommend to `GitProgressAutoClose origAutoClose = progress.m_AutoClose;` save the valud before overwriting it and then check `if (origAutoClose == AUTOCLOSE_NO)`.

**Comment by YueLinHo** [comment]
> I haven't said anything about L"" or _T"". as this is clearly a side issue, which can be addressed by us. So, no need to care for you.

Yap! :smiley:   

@AJH16 Sorry, I am kind of picky.
And thanks for your contribution. :+1:

**Comment by csware** [comment]
@AJH16 Are you going to update this PR (as mentioned in https://github.com/TortoiseGit/TortoiseGit/pull/198#issuecomment-223022779)? I'd like to release a new preview release and this fix should be included ;)

**Comment by AJH16** [comment]
Yes. sorry, I am not configured at home and get a limited amount of time at work to spend on this.  I have more time today though, so I'll be submitting it today.

**Comment by AJH16** [comment]
Ok, it should be ready.  I hadn't tested prior to pushing and then remembered it would go straight to the pull request.  It is tested now and appears to work fine.  It occurs to me that it might make sense to move the check of "isStash" to the method as well, but I didn't want to alter things that much.

**Comment by AJH16** [comment]
Odd, I updated to fix the merge conflicts on the changelog.  Any idea why CI didn't pick up on that and run?

**Comment by YueLinHo** [comment]
> Odd, I updated to fix the merge conflicts on the changelog. Any idea why CI didn't pick up on that and run?

The result of Appveyor is PASS. See [master.859](https://ci.appveyor.com/project/TortoiseGit/tortoisegit/build/master.859)
So, maybe network problem somewhere.

**Comment by csware** [comment]
Right now I wonder whether it is better to introduce a "quiet" or "silent" parameter, since the result messagebox might be interesting to people who set autoclose to 2 but want to see the results...

**Comment by AJH16** [comment]
What would the use case be for autoclose 2 then.  I'm trying to think of when you would want to autoclose on success but also see just popup notifications.  It means you specifically are asking the window to close as long as there are no errors and everything completes successfully.  Not that more granularity isn't pretty much always good, but I'm struggling to imagine the use case.

**Comment by AJH16** [comment]
On the automation thing, it is also probably worth pointing out that for TortoiseSVN anyway, it is actually listed as the preferred way to do automation scripts (https://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-automation.html)  Not that TortoiseGit needs to maintain exact parity, but that's where my expectation of it came from.

**Comment by csware** [comment]
We also state

> Remember that TortoiseGit is a GUI client, and this automation guide shows you how to make the TortoiseGit dialogs appear to collect user input. If you want to write a script which requires no input, you should use the official Git command line client instead. 

i.e., unattended automation is no goal of TortoiseGit.

Autoclose right now is only for the git.exe dialog and I think we should not mix up hiding of helpful messageboxes and the progress dialog.

**Comment by AJH16** [comment]
I can see that argument. What would be the benefit of auto closing the one and not the other? It seems like you have a use case in mind.  I'm probably a bit too removed from the variety of ways people use it to see the use case. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by AJH16** [comment]
Actually I just thought of one too.  Yeah. I see what you are saying. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by AJH16** [comment]
Closing as there are use cases where this may be desired behavior.

**Pull request closed without merging**
