### PR TITLE
BrowseRefsDlg: Allow to configure tracked branches

### PR DESCRIPTION
**Pull request by csware**
Fixes https://code.google.com/p/tortoisegit/issues/detail?id=2490

### CODE REVIEW

**Comment by ch3cooli** [comment]
Could you rebase onto master @ c5a327c?
Then handle nested local branches

**Comment by csware** [comment]
Rebased

**Comment by ch3cooli** [comment]
Free free to merge.

**Comment by csware** [comment]
@ch3cooli Thank you for having a look and especially for spotting and fixing c5a327c3b827c209115b2be3df2b880b9f0245b9.

Merged.

**Pull request closed without merging**
