### PR TITLE
Fixes #3707 Adds callout for title/description on 50/72

### PR DESCRIPTION
**Pull request by billrob**
The title is restricted to 50 characters
The description is restricted to 72 characters
Updates Copyright in CommitDlg

### CODE REVIEW

**Comment by csware** [comment]
Thanks for the PR!

There already is some indicator functionality:  https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html#tgit-dug-settings-dialogs3

**Comment by csware** [comment]
Cross-ref: https://gitlab.com/tortoisegit/tortoisegit/-/issues/3707

**Comment by billrob** [comment]
Border would kinda work, but doesn't follow the spirit of 50 char limit for the title (first line) and 72 for subsequent lines.  Those restrictions work nicely for command line tooling.  If you have a pull request where someone added a setting, if I put it there as a checkbox for "Enforce 50/72 rule" ?

**Comment by csware** [comment]
I would prefer if the new feature could be integerated with the old one.

**Comment by billrob** [comment]
@csware I don't follow what you are asking.

**Comment by csware** [comment]
I like this feature, however, the current implementation is too invasive and not configurable. Not all people want to have a 50 characters limit on the first line.

TortoiseGit already allows to configure a horizontal line (border) in the commit message box (cf. <https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html#tgit-dug-settings-dialogs3>). Here the question is, how this could be integrated. I though of having the border based on the line number (if that is possible; e.g., 50 on the first line and 70 on later lines and having two settings in the options dialog for the first line and following lines - this way we could keep compatibility with older versions).

We could also have a hint indicating that there should be an empty line between the subject and the body. But I'm not sure how to do that.

Design ideas are welcome!

**Comment by billrob** [comment]
I never did win32 UI programming; I wanted to have a config switch, but got into those dialogs and didn't know how to do it.  What about a checkbox for 50/72 style commit messages, and we trigger the UI length warnings?  We don't worry about enforcing the empty line between title and body and we inject the blank line if it isn't there when we make the commit.

That would be the least amount of behavioral changes.

**Comment by csware** [comment]
I'm not an UI designer, so it would be really helpful to get idea. The actual coding can be done by me after we have a nice concept.

Sorry it takes so long.

**Comment by lanmanck** [comment]
Why not use Qt and be a cross-platform app?

**Pull request closed without merging**
