### PR TITLE
Adjust git-switch dialog drop-down list height

### PR DESCRIPTION
**Pull request by beru**
This makes git-switch dialog's drop-down lists a bit longer.

### CODE REVIEW

**Comment by csware** [comment]
I'm unsure whether we should pick this. - There are also other ideas on how to improve the branch selection dialogs (see issue #[1857](https://tortoisegit.org/issue/1857)).

At least in this version it is inconsistent with other dialogs such as the merge dialog.

**Comment by csware** [comment]
@beru Can you please rebase and make it consistent with other dialogs such as the merge dialog?

**Comment by beru** [comment]
@csware Sure. See you in a bit!

**Comment by beru** [comment]
@csware Rebased and force-pushed the PR branch. Please kindly review the change. Thanks.

**Comment by csware** [comment]
Merged with commit 3483e6638ea173d340e94e3f6c63554454160a6b with some modifications.

**Pull request closed without merging**
